/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myapp.wage_calc;

import javax.swing.JOptionPane;

/**
 *
 * @author Alif
 */
public class Wage_Calc extends javax.swing.JFrame {

    /**
     * Creates new form wage_Calcu
     */
    public Wage_Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        golongan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tunjangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        potongan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total_gaji = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GAJI PEGAWAI");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NIK                  :");

        nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama               :");

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin :");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setText("Perempuan");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Laki-Laki");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Golongan         :");

        golongan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        golongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Option", "1a", "1b", "1c", "1d", "2a", "2b", "2c", "2d", "3a", "3b", "3c", "3d", "4a", "4b", "4c", "4d", "4e" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tunjangan      :");

        tunjangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Gaji        :");

        potongan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Potongan        :");

        total_gaji.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_gaji.setForeground(new java.awt.Color(255, 51, 51));
        total_gaji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_gaji.setText("Result");
        total_gaji.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(golongan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(potongan, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(submit)
                                            .addGap(18, 18, 18)
                                            .addComponent(reset))
                                        .addComponent(tunjangan, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addComponent(total_gaji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nik, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(name))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(golongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potongan)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(nik.getText().equals("") || name.getText().equals("") || golongan.getSelectedItem().equals("Select an Option") || tunjangan.getText().equals("") || potongan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tolong Masukan Data yang tertera", "ERROR MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } else if(golongan.getSelectedItem().equals("1a")){
            int gapok = 2335800;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("1b")){
            int gapok = 2472900;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("1c")){
            int gapok = 2577500;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("1d")){
            int gapok = 2686500;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("2a")){
            int gapok = 3373600;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("2b")){
            int gapok = 3516300;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("2c")){
            int gapok = 3665000;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("2d")){
            int gapok = 3820000;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("3a")){
            int gapok = 4236400;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("3b")){
            int gapok = 4415600;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("3c")){
            int gapok = 4602400;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("3d")){
            int gapok = 4797000;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("4a")){
            int gapok = 5000000;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("4b")){
            int gapok = 5211500;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("4c")){
            int gapok = 5431900;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("4d")){
            int gapok = 5661700;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        } else if(golongan.getSelectedItem().equals("4e")){
            int gapok = 5901200;
            int tunj = Integer.parseInt(tunjangan.getText());
            int pot = Integer.parseInt(potongan.getText());
            int total = (gapok + tunj) - pot;

            total_gaji.setText("Rp. "+total);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nik.setText("");
        name.setText("");
        buttonGroup1.clearSelection();
        golongan.setSelectedIndex(0);
        tunjangan.setText("");
        potongan.setText("");
        total_gaji.setText("Result");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wage_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wage_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wage_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wage_Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wage_Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> golongan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField potongan;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JLabel total_gaji;
    private javax.swing.JTextField tunjangan;
    // End of variables declaration//GEN-END:variables
}
